jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout student submission
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.student_repo_link }}
          path: student-code
        continue-on-error: true

      - name: Run tests
        if: steps.checkout.outcome == 'success'
        run: |
          mkdir -p reports
          SUBMISSION_ID="${{ github.event.client_payload.submission_id }}"

          if [ -f "student-code/a.txt" ]; then
            echo "{\"submission_id\":\"$SUBMISSION_ID\",\"passed\":1,\"total\":1,\"results\":{\"message\":\"a.txt found\"}}" > reports/$SUBMISSION_ID.json
          else
            echo "{\"submission_id\":\"$SUBMISSION_ID\",\"passed\":0,\"total\":1,\"results\":{\"message\":\"a.txt not found\"}}" > reports/$SUBMISSION_ID.json
          fi

      - name: Generate error report
        if: always() && steps.checkout.outcome != 'success'
        run: |
          mkdir -p reports
          SUBMISSION_ID="${{ github.event.client_payload.submission_id }}"

          echo "{
            \"submission_id\":\"$SUBMISSION_ID\",
            \"passed\":0,
            \"total\":0,
            \"error\":\"Repository could not be cloned.\"
          }" > reports/$SUBMISSION_ID.json

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ github.event.client_payload.submission_id }}
          path: reports/${{ github.event.client_payload.submission_id }}.json

      - name: Send result to backend
        if: always()
        run: |
          curl -X POST ${{ secrets.BACKEND_URL }}/api/submissions/callback \
            -H "Content-Type: application/json" \
            -H "X-Callback-Secret: ${{ secrets.CALLBACK_SECRET }}" \
            -d @reports/${{ github.event.client_payload.submission_id }}.json